name: Demo_actions

on:
  #triggers
  push:
    branches: ["main", "github-secrets"]
  # to manually trigger the workflow 
  workflow_dispatch:

jobs:
  #job name (demo_build)
  demo_build:
    # on which runner our code is going to run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a demo script
        run: echo ${{ secrets.MESSAGE }}
      - name: Run a mutli-line script
        run: |
          echo Hi
          echo Hello!
          
  
